### ISSUE TITLE
Inicjalizacja projektu modułu klienta

### ISSUE THREAD

**Issue by Michalski-Artur** [pw-software-engineering/n-team#1]
- [x] Create a basic ASP.NET core project
- [x] Create skeleton UI (PoC)
- [x] Sprawdzić winforms  https://stackoverflow.com/questions/57750630/containerize-c-sharp-winforms-applications (Abandoning WinForms, using ASP.NET Core as a Web App)

Time spent: 3h (current sprint); 13h (previous sprint)
