### ISSUE TITLE
Docker CI/CD

### ISSUE THREAD

**Issue by cyaneko** [pw-software-engineering/n-team#20]
- [x] Generate and test SQL Server image with modules outside containers
- [x] Every project generates a docker image locally
- [x] All docker images are deployed to an external service

**Comment by cyaneko** [comment]
Four hours have passed and I unfortunately need more time to take care of this.
