### ISSUE TITLE
[Client UI] Selenium tests

### ISSUE THREAD

**Issue by mtabor99-pw** [pw-software-engineering/n-team#50]
- [x] Selenium unit tests project initialization
- [ ] UI tests for client login page + validation
- [ ] UI tests for client account management + validation
- [ ] UI tests for hotel search + validation + hotel details
- [ ] UI tests for offer search + validation + offer details
- [ ] UI tests for reservation creation + validation
- [ ] UI tests for client reservations
