### ISSUE TITLE
[Client UI] UI logic implementation

### ISSUE THREAD

**Issue by mtabor99-pw** [pw-software-engineering/n-team#51]
- [x] UI logic for client login
- [x] login API mockup
- [x] UI logic for client account management + validation
- [x] client account management API mockup
- [x] UI logic for hotel search + filter validation
- [x] hotel search API mockup
- [x] UI logic for hotel details
- [x] hotel details API mockup
- [ ] UI logic for offer search + filter validation
- [ ] offer search API mockup
- [ ] UI logic for offer details + offer reviews
- [ ] offer details and reviews API mockup
- [ ] UI logic for reservation creation
- [ ] reservation creation API mockup
- [x] UI logic for client reservations
- [x] client reservation API mockup
- [x] UI logic for client reviews + validation
- [x] client reviews API mockup
